### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by javiermarcon** [theirix/redmine_autoclose#1]
Thanks for developing the plugin. When I try to run the plugin I get this error:

cd /usr/share/redmine/apps/redmine/htdocs && /usr/share/redmine/ruby/bin/bundle exec rake autoclose:autoclose RAILS_ENV=production 2>&1
rake aborted!
You have already activated rake 0.9.2.2, but your Gemfile requires rake 10.1.0. Using bundle exec may solve this.
(See full trace by running task with --trace)

If I run:

cd /usr/share/redmine/apps/redmine/htdocs && bin/rake autoclose:autoclose RAILS_ENV=production > /tmp/log.txt 2>&1

I get no error but the issues are not closed.

How can I fix it? How can I make the plugin appy to all projects, is there a wildcard for the projects configuration?

Thanks.

**Comment by theirix** [comment]
Hello.
Thank you for trying using the plugin. First error seems like as an error with redmine installation, maybe with Gemfile.lock which needs `bundle install` run but I am not sure.
1. Could you please check what is logged by the plugin to standard output (/tmp/log.txt for your run)?
2. How you configured the plugin?

Nice idea about the wildcarding of all projects, I'll implement it a little later.

**Comment by javiermarcon** [comment]
Thanks, the script does not produce any output in stdout or stderr. In all cases, standard output and standard error are empty (and therefore log.txt is empty). I ran:

./gem update rake
cd /usr/share/redmine/apps/redmine/htdocs/ && /usr/share/redmine/ruby/bin/bundle exec /usr/share/redmine/ruby/bin/rake autoclose:autoclose RAILS_ENV=production 2>&1

But this lead to the same error than before, but changing the installed version, so then I ran: 

./gem uninstall rake
./gem install rake -v 10.1.0
cd /usr/share/redmine/apps/redmine/htdocs/ && /usr/share/redmine/ruby/bin/bundle exec /usr/share/redmine/ruby/bin/rake autoclose:autoclose RAILS_ENV=production 2>&1

This last commands made the plugin to run without giving an error but the plugin does not close any solved issue.

Is there any debugging options to tell what does the plugin do?

**Comment by theirix** [comment]
There is no extra debug information, I can add a few.
Are you sure there are any issues in project Y that have been resolved more than X days ago where X is a "check interval " setting and Y is a project identifier specified in "Identifier" field in project settings (usually it is a alphanumeric string without spaces)?

**Comment by javiermarcon** [comment]
Thanks, I have almost 20 issues in state "resolved" with more than 90 days of resolution in all the projects, My settings are:

check interval: 90 
User Who closes: Mario (Administrator account)
Note text: Issue is closed.
Included projects: TREMé,Cliente Automotive,Produtora De Comercio

The names of the projects have accents and spaces, do that influence the processing of incidents?

**Comment by theirix** [comment]
You need to specify project identifiers not names. They can be found in
project settings page.

---

Best regards,
Eugene Seliverstov

**Comment by javiermarcon** [comment]
Thanks, I changed the included projects option filling it with project identifiers, but I running the command doesn't close the issues (and does not produce any output to stdout or stderr).

The command I run is:
cd /usr/share/redmine/apps/redmine/htdocs/ && /usr/share/redmine/ruby/bin/bundle exec /usr/share/redmine/ruby/bin/rake autoclose:autoclose RAILS_ENV=production 2>&1

**Comment by theirix** [comment]
Thank you for the information. Please run the plugin version from 'debug' branch and provide the stderr output.

**Comment by theirix** [comment]
Sorry, I added changes just now. Check the 'debug' branch.

**Comment by javiermarcon** [comment]
Thanks, I ran it in debug mode but it still leaves unclosed the resolved incidents.

mzito@mail:/usr/share/redmine/apps/redmine/htdocs/plugins/redmine_autoclose$ git branch
- master
  mzito@mail:/usr/share/redmine/apps/redmine/htdocs/plugins/redmine_autoclose$ git fetch
  remote: Counting objects: 5, done.
  remote: Compressing objects: 100% (5/5), done.
  remote: Total 5 (delta 0), reused 0 (delta 0), pack-reused 0
  Unpacking objects: 100% (5/5), done.
  From https://github.com/theirix/redmine_autoclose
  - [new branch]      debug      -> origin/debug
    mzito@mail:/usr/share/redmine/apps/redmine/htdocs/plugins/redmine_autoclose$ git checkout debug
    Branch debug set up to track remote branch debug from origin.
    Switched to a new branch 'debug'
    mzito@mail:/usr/share/redmine/apps/redmine/htdocs/plugins/redmine_autoclose$ git pull 
    Already up-to-date.
    mzito@mail:/usr/share/redmine/apps/redmine/htdocs/plugins/redmine_autoclose$ cd /usr/share/redmine/apps/redmine/htdocs/ && /usr/share/redmine/ruby/bin/bundle exec /usr/share/redmine/ruby/bin/rake autoclose:preview RAILS_ENV=production 2>&1
    redmine_autoclose: interval 2016-04-30 14:21:17 UTC, ids ["treme", "acs-automotive", "aerolom", "bodegas-salentein", "compass-group", "treme-conector", "treme-generales", "suma-consultora"]
    mzito@mail:/usr/share/redmine/apps/redmine/htdocs$ cd /usr/share/redmine/apps/redmine/htdocs/ && /usr/share/redmine/ruby/bin/bundle exec /usr/share/redmine/ruby/bin/rake autoclose:autoclose RAILS_ENV=production 2>&1
    redmine_autoclose: interval 2016-04-30 14:21:55 UTC, ids ["treme", "acs-automotive", "aerolom", "bodegas-salentein", "compass-group", "treme-conector", "treme-generales", "suma-consultora"]
    mzito@mail:/usr/share/redmine/apps/redmine/htdocs$ 

In the mmain project is treme (id treme, name TREMé), the other listed projects like treme-generales are subprojects of treme.

In treme-generales for example I have many resolved icidents from 2014, 2015, 2016, etc.

**Comment by theirix** [comment]
I added a few more debug statements. Could you please update and run again? Also what is your redmine version and was it installed manually or via package manager?

**Comment by javiermarcon** [comment]
Thanks, this is the result:

mzito@mail:/usr/share/redmine/apps/redmine/htdocs/plugins/redmine_autoclose$ git pull 
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 5 (delta 2), reused 5 (delta 2), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/theirix/redmine_autoclose
   8d6c037..4a1eb2d  debug      -> origin/debug
Updating 8d6c037..4a1eb2d
Fast-forward
 lib/redmine_autoclose/autoclose.rb |    2 ++
 1 file changed, 2 insertions(+)
mzito@mail:/usr/share/redmine/apps/redmine/htdocs/plugins/redmine_autoclose$ cd /usr/share/redmine/apps/redmine/htdocs/ && /usr/share/redmine/ruby/bin/bundle exec /usr/share/redmine/ruby/bin/rake autoclose:preview RAILS_ENV=production 2>&1
redmine_autoclose: interval 2016-04-30 15:17:06 UTC, ids ["treme", "acs-automotive", "aerolom", "bodegas-salentein", "compass-group", "treme-conector", "treme-generales", "suma-consultora"]
redmine_autoclose: issues #<IssueStatus id: 1, name: "Nueva", is_closed: false, is_default: true, position: 1, default_done_ratio: 0>#<IssueStatus id: 2, name: "En curso", is_closed: false, is_default: false, position: 2, default_done_ratio: 50>#<IssueStatus id: 3, name: "Resuelta", is_closed: false, is_default: false, position: 3, default_done_ratio: 80>#<IssueStatus id: 4, name: "Feedback", is_closed: false, is_default: false, position: 4, default_done_ratio: 90>#<IssueStatus id: 5, name: "Cerrada", is_closed: true, is_default: false, position: 5, default_done_ratio: 100>#<IssueStatus id: 6, name: "Rechazada", is_closed: true, is_default: false, position: 6, default_done_ratio: 0>, choosen: 
redmine_autoclose: looking to 9
redmine_autoclose: looking to 16
redmine_autoclose: looking to 17
redmine_autoclose: looking to 18
redmine_autoclose: looking to 19
redmine_autoclose: looking to 20
redmine_autoclose: looking to 22
redmine_autoclose: looking to 23
mzito@mail:/usr/share/redmine/apps/redmine/htdocs$ cd /usr/share/redmine/apps/redmine/htdocs/ && /usr/share/redmine/ruby/bin/bundle exec /usr/share/redmine/ruby/bin/rake autoclose:autoclose RAILS_ENV=production 2>&1
redmine_autoclose: interval 2016-04-30 15:17:29 UTC, ids ["treme", "acs-automotive", "aerolom", "bodegas-salentein", "compass-group", "treme-conector", "treme-generales", "suma-consultora"]
redmine_autoclose: issues #<IssueStatus id: 1, name: "Nueva", is_closed: false, is_default: true, position: 1, default_done_ratio: 0>#<IssueStatus id: 2, name: "En curso", is_closed: false, is_default: false, position: 2, default_done_ratio: 50>#<IssueStatus id: 3, name: "Resuelta", is_closed: false, is_default: false, position: 3, default_done_ratio: 80>#<IssueStatus id: 4, name: "Feedback", is_closed: false, is_default: false, position: 4, default_done_ratio: 90>#<IssueStatus id: 5, name: "Cerrada", is_closed: true, is_default: false, position: 5, default_done_ratio: 100>#<IssueStatus id: 6, name: "Rechazada", is_closed: true, is_default: false, position: 6, default_done_ratio: 0>, choosen: 
redmine_autoclose: looking to 9
redmine_autoclose: looking to 16
redmine_autoclose: looking to 17
redmine_autoclose: looking to 18
redmine_autoclose: looking to 19
redmine_autoclose: looking to 20
redmine_autoclose: looking to 22
redmine_autoclose: looking to 23
mzito@mail:/usr/share/redmine/apps/redmine/htdocs$

**Comment by theirix** [comment]
Thank you. It seems a problem is with resolved status name. Could you please check issue names at http://YOUR_HOST/issue_statuses ? Is there a 'Resolved' issue status? What about Redmine version?

**Comment by javiermarcon** [comment]
Ruby is 1.9.1, I don't find redmine version, but I think is Bitnami Redmine 2.4

**Comment by javiermarcon** [comment]
Thanks, issue_statuses gives me a number: 406

**Comment by theirix** [comment]
Oh, 2.4 is an extremely old version and I had not tested plugin for 2.4.
About issue_statuses - seems it is a different url for Redmine 2.4. I meant a settings page where you are configuring issue statuses. Could you check it?

**Comment by javiermarcon** [comment]
Thanks, I will try to chek it.

**Comment by javiermarcon** [comment]
Thanks. According to the log of your plugin, the resolved state is Resuelta:
#<IssueStatus id: 1, name: "Nueva", is_closed: false, is_default: true, position: 1, default_done_ratio: 0>
#<IssueStatus id: 2, name: "En curso", is_closed: false, is_default: false, position: 2, default_done_ratio: 50>
#<IssueStatus id: 3, name: "Resuelta", is_closed: false, is_default: false, position: 3, default_done_ratio: 80>
#<IssueStatus id: 4, name: "Feedback", is_closed: false, is_default: false, position: 4, default_done_ratio: 90>
#<IssueStatus id: 5, name: "Cerrada", is_closed: true, is_default: false, position: 5, default_done_ratio: 100>
#<IssueStatus id: 6, name: "Rechazada", is_closed: true, is_default: false, position: 6, default_done_ratio: 0>

I changed Resolved for Resuelta in lib/redmine_autoclose/autoclose.rb and now I have this output:

mzito@mail:/usr/share/redmine/apps/redmine/htdocs$ cd /usr/share/redmine/apps/redmine/htdocs/ && /usr/share/redmine/ruby/bin/bundle exec /usr/share/redmine/ruby/bin/rake autoclose:autoclose RAILS_ENV=production 2>&1
redmine_autoclose: interval 2016-04-30 17:29:09 UTC, ids ["treme", "acs-automotive", "aerolom", "bodegas-salentein", "compass-group", "treme-conector", "treme-generales", "suma-consultora"]
redmine_autoclose: issues #<IssueStatus id: 1, name: "Nueva", is_closed: false, is_default: true, position: 1, default_done_ratio: 0>#<IssueStatus id: 2, name: "En curso", is_closed: false, is_default: false, position: 2, default_done_ratio: 50>#<IssueStatus id: 3, name: "Resuelta", is_closed: false, is_default: false, position: 3, default_done_ratio: 80>#<IssueStatus id: 4, name: "Feedback", is_closed: false, is_default: false, position: 4, default_done_ratio: 90>#<IssueStatus id: 5, name: "Cerrada", is_closed: true, is_default: false, position: 5, default_done_ratio: 100>#<IssueStatus id: 6, name: "Rechazada", is_closed: true, is_default: false, position: 6, default_done_ratio: 0>, choosen: Resuelta
redmine_autoclose: looking to 9
rake aborted!
undefined method `detail_for_attribute' for #<Journal:0x000000064f4358>
/media/datos/redmine/apps/redmine/htdocs/vendor/bundle/ruby/1.9.1/gems/activemodel-3.2.16/lib/active_model/attribute_methods.rb:407:in`method_missing'
/media/datos/redmine/apps/redmine/htdocs/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.16/lib/active_record/attribute_methods.rb:149:in `method_missing'
/media/datos/redmine/apps/redmine/htdocs/plugins/redmine_autoclose/lib/redmine_autoclose/autoclose.rb:7:in`block in when_issue_resolved'
/media/datos/redmine/apps/redmine/htdocs/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.16/lib/active_record/associations/collection_proxy.rb:91:in `reverse_each'
/media/datos/redmine/apps/redmine/htdocs/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.16/lib/active_record/associations/collection_proxy.rb:91:in`method_missing'
/media/datos/redmine/apps/redmine/htdocs/plugins/redmine_autoclose/lib/redmine_autoclose/autoclose.rb:6:in `when_issue_resolved'
/media/datos/redmine/apps/redmine/htdocs/plugins/redmine_autoclose/lib/redmine_autoclose/autoclose.rb:19:in`block (2 levels) in enumerate_issues'
/media/datos/redmine/apps/redmine/htdocs/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.16/lib/active_record/relation/delegation.rb:6:in `each'
/media/datos/redmine/apps/redmine/htdocs/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.16/lib/active_record/relation/delegation.rb:6:in`each'
/media/datos/redmine/apps/redmine/htdocs/plugins/redmine_autoclose/lib/redmine_autoclose/autoclose.rb:18:in `block in enumerate_issues'
/media/datos/redmine/apps/redmine/htdocs/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.16/lib/active_record/relation/delegation.rb:6:in`each'
/media/datos/redmine/apps/redmine/htdocs/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.16/lib/active_record/relation/delegation.rb:6:in `each'
/media/datos/redmine/apps/redmine/htdocs/plugins/redmine_autoclose/lib/redmine_autoclose/autoclose.rb:16:in`enumerate_issues'
/media/datos/redmine/apps/redmine/htdocs/plugins/redmine_autoclose/lib/redmine_autoclose/autoclose.rb:40:in `autoclose'
/media/datos/redmine/apps/redmine/htdocs/plugins/redmine_autoclose/lib/tasks/autoclose.rake:7:in`block (2 levels) in <top (required)>'
Tasks: TOP => autoclose:autoclose
(See full trace by running task with --trace)
mzito@mail:/usr/share/redmine/apps/redmine/htdocs$

**Comment by javiermarcon** [comment]
Thanks, this is the run with --trace:

mzito@mail:/usr/share/redmine/apps/redmine/htdocs$ cd /usr/share/redmine/apps/redmine/htdocs/ && /usr/share/redmine/ruby/bin/bundle exec /usr/share/redmine/ruby/bin/rake --trace autoclose:autoclose RAILS_ENV=production 2>&1
*\* Invoke autoclose:autoclose (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute autoclose:autoclose
redmine_autoclose: interval 2016-04-30 17:34:32 UTC, ids ["treme", "acs-automotive", "aerolom", "bodegas-salentein", "compass-group", "treme-conector", "treme-generales", "suma-consultora"]
redmine_autoclose: issues #<IssueStatus id: 1, name: "Nueva", is_closed: false, is_default: true, position: 1, default_done_ratio: 0>#<IssueStatus id: 2, name: "En curso", is_closed: false, is_default: false, position: 2, default_done_ratio: 50>#<IssueStatus id: 3, name: "Resuelta", is_closed: false, is_default: false, position: 3, default_done_ratio: 80>#<IssueStatus id: 4, name: "Feedback", is_closed: false, is_default: false, position: 4, default_done_ratio: 90>#<IssueStatus id: 5, name: "Cerrada", is_closed: true, is_default: false, position: 5, default_done_ratio: 100>#<IssueStatus id: 6, name: "Rechazada", is_closed: true, is_default: false, position: 6, default_done_ratio: 0>, choosen: Resuelta
redmine_autoclose: looking to 9
rake aborted!
undefined method `detail_for_attribute' for #<Journal:0x00000004fd4810>
/media/datos/redmine/apps/redmine/htdocs/vendor/bundle/ruby/1.9.1/gems/activemodel-3.2.16/lib/active_model/attribute_methods.rb:407:in`method_missing'
/media/datos/redmine/apps/redmine/htdocs/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.16/lib/active_record/attribute_methods.rb:149:in `method_missing'
/media/datos/redmine/apps/redmine/htdocs/plugins/redmine_autoclose/lib/redmine_autoclose/autoclose.rb:7:in`block in when_issue_resolved'
/media/datos/redmine/apps/redmine/htdocs/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.16/lib/active_record/associations/collection_proxy.rb:91:in `reverse_each'
/media/datos/redmine/apps/redmine/htdocs/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.16/lib/active_record/associations/collection_proxy.rb:91:in`method_missing'
/media/datos/redmine/apps/redmine/htdocs/plugins/redmine_autoclose/lib/redmine_autoclose/autoclose.rb:6:in `when_issue_resolved'
/media/datos/redmine/apps/redmine/htdocs/plugins/redmine_autoclose/lib/redmine_autoclose/autoclose.rb:19:in`block (2 levels) in enumerate_issues'
/media/datos/redmine/apps/redmine/htdocs/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.16/lib/active_record/relation/delegation.rb:6:in `each'
/media/datos/redmine/apps/redmine/htdocs/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.16/lib/active_record/relation/delegation.rb:6:in`each'
/media/datos/redmine/apps/redmine/htdocs/plugins/redmine_autoclose/lib/redmine_autoclose/autoclose.rb:18:in `block in enumerate_issues'
/media/datos/redmine/apps/redmine/htdocs/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.16/lib/active_record/relation/delegation.rb:6:in`each'
/media/datos/redmine/apps/redmine/htdocs/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.16/lib/active_record/relation/delegation.rb:6:in `each'
/media/datos/redmine/apps/redmine/htdocs/plugins/redmine_autoclose/lib/redmine_autoclose/autoclose.rb:16:in`enumerate_issues'
/media/datos/redmine/apps/redmine/htdocs/plugins/redmine_autoclose/lib/redmine_autoclose/autoclose.rb:40:in `autoclose'
/media/datos/redmine/apps/redmine/htdocs/plugins/redmine_autoclose/lib/tasks/autoclose.rake:7:in`block (2 levels) in <top (required)>'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:236:in `call'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:236:in`block in execute'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:231:in `each'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:231:in`execute'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/usr/share/redmine/ruby/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:161:in`invoke'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:149:in `invoke_task'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:106:in`block (2 levels) in top_level'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:106:in `each'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:106:in`block in top_level'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:115:in `run_with_threads'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:100:in`top_level'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:78:in `block in run'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:165:in`standard_exception_handling'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:75:in `run'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/bin/rake:33:in`<top (required)>'
/usr/share/redmine/ruby/bin/rake:23:in `load'
/usr/share/redmine/ruby/bin/rake:23:in`<main>'
Tasks: TOP => autoclose:autoclose
mzito@mail:/usr/share/redmine/apps/redmine/htdocs$

**Comment by theirix** [comment]
Great, I see the problem. Please check the 'debug' branch again.

**Comment by javiermarcon** [comment]
Thanks, I got another error:

mzito@mail:/usr/share/redmine/apps/redmine/htdocs/plugins/redmine_autoclose$ cd /usr/share/redmine/apps/redmine/htdocs/ && /usr/share/redmine/ruby/bin/bundle exec /usr/share/redmine/ruby/bin/rake --trace autoclose:autoclose RAILS_ENV=production 2>&1
*\* Invoke autoclose:autoclose (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Execute autoclose:autoclose
redmine_autoclose: interval 2016-04-30 17:58:54 UTC, ids ["treme", "acs-automotive", "aerolom", "bodegas-salentein", "compass-group", "treme-conector", "treme-generales", "suma-consultora"]
redmine_autoclose: issues #<IssueStatus id: 1, name: "Nueva", is_closed: false, is_default: true, position: 1, default_done_ratio: 0>#<IssueStatus id: 2, name: "En curso", is_closed: false, is_default: false, position: 2, default_done_ratio: 50>#<IssueStatus id: 3, name: "Resuelta", is_closed: false, is_default: false, position: 3, default_done_ratio: 80>#<IssueStatus id: 4, name: "Feedback", is_closed: false, is_default: false, position: 4, default_done_ratio: 90>#<IssueStatus id: 5, name: "Cerrada", is_closed: true, is_default: false, position: 5, default_done_ratio: 100>#<IssueStatus id: 6, name: "Rechazada", is_closed: true, is_default: false, position: 6, default_done_ratio: 0>, choosen: Resuelta
redmine_autoclose: looking to 9
redmine_autoclose: checking issue 74 of project '9' with date 2014-05-20 19:47:43 UTC => true
Autoclosing issue #74 (Blog tremé)
redmine_autoclose: checking issue 258 of project '9' with date 2014-12-29 18:24:42 UTC => true
Autoclosing issue #258 (Fecha de registros en el tablero)
redmine_autoclose: checking issue 261 of project '9' with date 2014-12-30 23:02:01 UTC => true
Autoclosing issue #261 (Que aparezca rotulo de campo en csv en lugar de aparecer la property)
redmine_autoclose: checking issue 274 of project '9' with date 2015-01-27 14:26:14 UTC => true
Autoclosing issue #274 (Ocultar campos en Vista del registro)
redmine_autoclose: checking issue 279 of project '9' with date 2015-04-21 14:13:31 UTC => true
Autoclosing issue #279 (Al seleccionar registros de hoy en producción no aparecen.)
rake aborted!
undefined method `<' for []:Array
/media/datos/redmine/apps/redmine/htdocs/plugins/redmine_autoclose/lib/redmine_autoclose/autoclose.rb:20:in`block (2 levels) in enumerate_issues'
/media/datos/redmine/apps/redmine/htdocs/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.16/lib/active_record/relation/delegation.rb:6:in `each'
/media/datos/redmine/apps/redmine/htdocs/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.16/lib/active_record/relation/delegation.rb:6:in`each'
/media/datos/redmine/apps/redmine/htdocs/plugins/redmine_autoclose/lib/redmine_autoclose/autoclose.rb:18:in `block in enumerate_issues'
/media/datos/redmine/apps/redmine/htdocs/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.16/lib/active_record/relation/delegation.rb:6:in`each'
/media/datos/redmine/apps/redmine/htdocs/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.16/lib/active_record/relation/delegation.rb:6:in `each'
/media/datos/redmine/apps/redmine/htdocs/plugins/redmine_autoclose/lib/redmine_autoclose/autoclose.rb:16:in`enumerate_issues'
/media/datos/redmine/apps/redmine/htdocs/plugins/redmine_autoclose/lib/redmine_autoclose/autoclose.rb:40:in `autoclose'
/media/datos/redmine/apps/redmine/htdocs/plugins/redmine_autoclose/lib/tasks/autoclose.rake:7:in`block (2 levels) in <top (required)>'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:236:in `call'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:236:in`block in execute'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:231:in `each'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:231:in`execute'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:175:in `block in invoke_with_call_chain'
/usr/share/redmine/ruby/lib/ruby/1.9.1/monitor.rb:211:in`mon_synchronize'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:168:in `invoke_with_call_chain'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/task.rb:161:in`invoke'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:149:in `invoke_task'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:106:in`block (2 levels) in top_level'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:106:in `each'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:106:in`block in top_level'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:115:in `run_with_threads'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:100:in`top_level'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:78:in `block in run'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:165:in`standard_exception_handling'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/lib/rake/application.rb:75:in `run'
/usr/share/redmine/ruby/lib/ruby/gems/1.9.1/gems/rake-10.1.0/bin/rake:33:in`<top (required)>'
/usr/share/redmine/ruby/bin/rake:23:in `load'
/usr/share/redmine/ruby/bin/rake:23:in`<main>'
Tasks: TOP => autoclose:autoclose
mzito@mail:/usr/share/redmine/apps/redmine/htdocs$

**Comment by javiermarcon** [comment]
Also in that last run, issue #74 should be closed by the plugin but checking in redmine it is still on resolved state.

Thanks.

**Comment by javiermarcon** [comment]
Do you need more information about issue #279 that is causing the error?

**Comment by theirix** [comment]
Thank you, I found a problem with the #279, please update and check again.
Also if you have 'Closed' issue state with name other than 'Closed' please change it in plugin too.

**Comment by javiermarcon** [comment]
Thanks, I will change it ald check, because my redmine is in spanish so Closed is Cerrada.
#<IssueStatus id: 5, name: "Cerrada", is_closed: true, is_default: false, position: 5, default_done_ratio: 100>

**Comment by javiermarcon** [comment]
Thanks, now it worked.

**Comment by theirix** [comment]
Glad to hear that! I have also update 'master' branch without debugging info. Do not forget to change issue status names.

**Comment by javiermarcon** [comment]
Thanks, I switched to that branch and changed the names, but now I don't have older resolved issues to test the plugin.

**Comment by theirix** [comment]
It's okay, I just moved changes between branches so they should be the same except of loigging.
