### ISSUE TITLE
update to 0.0.12, run rake not work.

### ISSUE THREAD

**Issue by TerenceYL** [theirix/redmine_autoclose#10]
it's show: NoMethodError: undefined method `map' for nil:NilClass

my redmine is 4.2.11.stable

trakder not seleted, will have this issue, 
if select a tracker that work fine.

**Comment by theirix** [comment]
Thank you for the report. Did you upgrade the plugin or just installed the latest version?

**Comment by TerenceYL** [comment]
> Thank you for the report. Did you upgrade the plugin or just installed the latest version?

I upgraded from 0.0.11
use > sudo git pull
