### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by fishermans** [theirix/redmine_autoclose#11]
Hi,
I would like to implement some improvements.

1. Wildcard support for projects. (have to manage more than 300)
2. Switch between identifiers or names (I have to go for names but don't want to brake existing installations)
3. API endpoint to call the rake task. I am running redmine on containers and want to setup a service container for the cron job instead of modifying the redmine container.

Do you except PR for those changes? Your thoughts?

THX

**Comment by theirix** [comment]
Hello @fishermans ,

Thank you for the ideas and the PR! I will take a look soon

**Comment by theirix** [comment]
Brushed up plugin a little. Thank you again for the contribution.
