### ISSUE TITLE
Include all project

### ISSUE THREAD

**Issue by Sabrimjd** [theirix/redmine_autoclose#2]
Hello Thank you for the plugin,
i have been wondering that if i dont put a project in the "Included projects" of the plugin does it take all the projects available ?

Thanks.

**Comment by theirix** [comment]
Hello!
Only projects listed in the "Included projects" will be checked by the plugin. So if a project is not in the list, it will not be checked.

**Comment by eviduka** [comment]
Thnx for the plugin, is there any workaround to include all projects when there is a lot projects? It doesn't take subprojects of a project into  account also, as I see. Is that possible? Thanks a lot!

**Comment by theirix** [comment]
I think I can add this.

**Comment by theirix** [comment]
Type * in project identifier list to select all projects.

**Comment by eviduka** [comment]
Tnx a lot!
