### ISSUE TITLE
Issue closing not sending notifications

### ISSUE THREAD

**Issue by jcasals** [theirix/redmine_autoclose#3]
Hello,

Thanks for your plugin, I have just installed it and it works great. My only concern is that in my test environment I saw the plugin was triggering the notification but then the notification is not sent. I thought it was a problem with my test environment but then in the production environment wasn't sent either.

I have been looking through the code but I'm not sure if there is something specific that I should configure or that the plugin doesn't send notifications.

My version of Redmine is 4.1.1 docker based and I have the last version of the autoclose plugin. It works, closes the issues fine, and I can set it up as a cron, but users don't get notifications when issues are closed.

Sorry for maybe asking a silly question, but I'm not much of an expert.

Thank you so much,

Jordi

**Comment by theirix** [comment]
Hello, Jordi,

Glad my plugin helps you!

I have fixed this problem, please check the latest version. Notification had not been sent because a Rake task had finished too fast and asynchronous email delivery couldn't complete in time. Probably this bug appeared when Redmine switched from sync to async email delivery.

**Comment by jcasals** [comment]
Wow, thank you so much for fixing this so fast! 
Let me download the last fix and try it this week. I'll get back to you to confirm it works for me.

Again, thank you!

**Comment by jcasals** [comment]
Hi @theirix, 

I can confirm that I tested it and it works.

Thank you again!

**Comment by theirix** [comment]
Great, you are welcom!
