### ISSUE TITLE
Make statuses configurable

### ISSUE THREAD

**Issue by pyguerder** [theirix/redmine_autoclose#4]
Hi @theirix,

Thank you very much for this plugin! We have the following issue: we are using translated values in `issue_statuses.name`, so I had to modify the plugin code to match the values that we use.

Would it be possible to make the "resolved" and "closed" statuses configurable please? I think it would also make the plugin more powerful because some may want to put the status from "comment" to "stale" after some days, etc.

Thanks a lot in advance

Best regards

**Comment by theirix** [comment]
Sure, I'll take a look soon

**Comment by pyguerder** [comment]
Wonderful! Another idea, from a colleague: it would be nice to allow ignoring closed/archived projects... Regards

**Comment by theirix** [comment]
I have added settings for issue statuses and active projects, please take a look.

**Comment by pyguerder** [comment]
Wonderful! Thank you very much!

**Comment by theirix** [comment]
Glad to help!
