### ISSUE TITLE
Attempted to update a stale object: Issue.

### ISSUE THREAD

**Issue by sajmun** [theirix/redmine_autoclose#6]
when running bundle exec rake autoclose:autoclose RAILS_ENV=production, some (under 10) isssue are closed, but after that we got error:
`rake aborted!
ActiveRecord::StaleObjectError: Attempted to update a stale object: Issue.
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/locking/optimistic.rb:96:in `_update_row'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/persistence.rb:719:in `_update_record'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/attribute_methods/dirty.rb:134:in `_update_record'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/callbacks.rb:350:in `block in _update_record'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-5.2.8/lib/active_support/callbacks.rb:132:in `run_callbacks'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-5.2.8/lib/active_support/callbacks.rb:816:in `_run_update_callbacks'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/callbacks.rb:350:in `_update_record'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/timestamp.rb:114:in `_update_record'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/persistence.rb:705:in `create_or_update'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/callbacks.rb:342:in `block in create_or_update'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-5.2.8/lib/active_support/callbacks.rb:132:in `run_callbacks'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-5.2.8/lib/active_support/callbacks.rb:816:in `_run_save_callbacks'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/callbacks.rb:342:in `create_or_update'
/home/redmine/redmine/app/models/issue.rb:227:in `create_or_update'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/persistence.rb:275:in `save'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/validations.rb:46:in `save'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/transactions.rb:310:in `block (2 levels) in save'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/transactions.rb:387:in `block in with_transaction_returning_status'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `block in transaction'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-5.2.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-5.2.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-5.2.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-5.2.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activesupport-5.2.8/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/connection_adapters/abstract/database_statements.rb:267:in `transaction'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/transactions.rb:212:in `transaction'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/transactions.rb:385:in `with_transaction_returning_status'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/transactions.rb:310:in `block in save'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/transactions.rb:325:in `rollback_active_record_state!'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/transactions.rb:309:in `save'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/suppressor.rb:44:in `save'
/home/redmine/redmine/plugins/redmine_autoclose/lib/redmine_autoclose/autoclose.rb:47:in `block (2 levels) in autoclose'
/home/redmine/redmine/plugins/redmine_autoclose/lib/redmine_autoclose/autoclose.rb:22:in `block (2 levels) in enumerate_issues'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/relation/delegation.rb:71:in `each'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/relation/delegation.rb:71:in `each'
/home/redmine/redmine/plugins/redmine_autoclose/lib/redmine_autoclose/autoclose.rb:20:in `block in enumerate_issues'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/relation/delegation.rb:71:in `each'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/activerecord-5.2.8/lib/active_record/relation/delegation.rb:71:in `each'
/home/redmine/redmine/plugins/redmine_autoclose/lib/redmine_autoclose/autoclose.rb:19:in `enumerate_issues'
/home/redmine/redmine/plugins/redmine_autoclose/lib/redmine_autoclose/autoclose.rb:41:in `block in autoclose'
/home/redmine/redmine/app/models/mailer.rb:649:in `with_synched_deliveries'
/home/redmine/redmine/plugins/redmine_autoclose/lib/redmine_autoclose/autoclose.rb:40:in `autoclose'
/home/redmine/redmine/plugins/redmine_autoclose/lib/tasks/autoclose.rake:7:in `block (2 levels) in <top (required)>'
/home/redmine/data/tmp/bundle/ruby/2.7.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => autoclose:autoclose
(See full trace by running task with --trace)
`
```

Environment:
  Redmine version                4.2.7.stable
  Ruby version                   2.7.5-p203 (2021-11-24) [x86_64-linux-gnu]
  Rails version                  5.2.8
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Subversion                     1.13.0
  Mercurial                      5.3.1
  Cvs                            1.12.13
  Bazaar                         3.0.2
  Git                            2.36.1
  Filesystem                     
Redmine plugins:
  clipboard_image_paste          1.13
  custom_field_sql               2.3
  redmine_autoclose              0.0.8
  redmine_custom_workflows       1.0.7
  redmine_impersonate            2.0.0
  redmine_live_relative_time     1.1
  redmine_mentions               0.0.1
  redmine_more_previews          2.0.7
  redmine_theme_changer          0.4.0
  redmine_web_forms              0.0.1
  redmine_wysiwyg_editor         0.23.0
  that_email_log                 0.0.4
```

**Comment by theirix** [comment]
Hello. It cannot be reproduced on my installation but I tried to fix it, please try it.

**Comment by sajmun** [comment]
thank you, it works
