### ISSUE TITLE
Allowing more than one 'Resolved status'

### ISSUE THREAD

**Issue by ini272** [theirix/redmine_autoclose#7]
Thanks for writing this plugin! I just tested this and it works out of the box. In my organization we have a lot of lingering tickets that get forgotten, so this will help clean up a bit :) I was wondering if more than one 'resolved status' could be considered for auto-closing. Often old tickets are also staying on the status 'Feedback' for example. Unfortunately, I lack the Ruby skills to add this, if you have a quick idea, let me know.

**Comment by theirix** [comment]
Glad the plugin helps you. Multiple status support is a good idea, I'll try to implement this.

**Comment by theirix** [comment]
I have implemented multiple resolved statuses. Tested it locally and at one of our production systems.
