### ISSUE TITLE
Apply plugin according to desired tracker(s)

### ISSUE THREAD

**Issue by mx5gr** [theirix/redmine_autoclose#8]
Great plugin!

It would be very helpful if there was a list of trackers that can be multiply selected, for which the autoclose conditions apply.

We want for example to autoclose all issues from tracker X and not for tracker Y within the same project.

Please consider it for a future release.

**Comment by theirix** [comment]
Thanks, good idea, I'll look into it.

**Comment by theirix** [comment]
I implemented this feature. All trackers are used by default, but you can customize a list in the settings.
