### ISSUE TITLE
Couting days since last update

### ISSUE THREAD

**Issue by M-Zaczek** [theirix/redmine_autoclose#9]
Hey man! I just find your plugin and instaled it. And It is very helpfull.
I dont know ruby much so I have a question.
It is possible to add feature (just checkbox I think) that will be count days from last update date in "resolved" statuses?

**Comment by theirix** [comment]
Hello.
Is the parameter "check interval" is what you need?
`check interval - amount of days after which an issue is treated as stalled.
`

So if an issue is in Resolved status for this number of days, then it is updated by the plugin with a comment.

**Comment by M-Zaczek** [comment]
Yes  I wrote about this parametr.
Tell me, are days counting from last update in certain status?
For example: IT dep change the request for Resolved after that someone from sales add comment. Days are counting from first set up od status or last issue change?

**Comment by M-Zaczek** [comment]
I close it by accident...

**Comment by theirix** [comment]
> Tell me, are days counting from last update in certain status?

Interval is counted from the day issue had been resolved. Comments after resolving do not count.

**Comment by theirix** [comment]
Closing as answered
